version: '3'

services:
  gdb:
    image: mysql:8.0.33
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABSE: root
      MYSQL_TCP_PORT: 3306
    restart: on-failure

  gapi:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
           "spring.datasource.url" : "jdbc:mysql://gdb:3306/Project-Management-Board-API-Specification?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true",
           "spring.datasource.password": "root"
        }'
    restart: on-failure
    depends_on:
      - gdb

  gui:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./src/main/resources/static:/usr/share/nginx/html
    restart: on-failure
    depends_on:
      - gapi